debug: False

home_assistant:
  host: 10.0.0.11
  ssl: False
  port: ~
  api_password: ~
  api_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI5ODIwNTRlN2NjOWI0ZTFkOTM2NWRjMTdjZjk3MDg0MyIsImlhdCI6MTU0MDcyMDI0OSwiZXhwIjoxODU2MDgwMjQ5fQ.LVZkReSK2vKliQWL6j0JaAKC6M877J_Ybeotzt0j8f8

streamdeck:
  brightness: 20

tiles:
  - type: "light"
    class: 'HassTile'
    states:
      - state: 'on'
        label: '{name}'
        label_font: Assets/Fonts/Roboto-Bold.ttf
        label_size: 12
        overlay: 'Assets/Images/light_on.png'
      - state: ~
        label: '{name}'
        label_font: Assets/Fonts/Roboto-Bold.ttf
        label_size: 12
        overlay: 'Assets/Images/light_off.png'
    action: 'toggle'

  - type: "automation"
    class: 'HassTile'
    states:
      - state: 'on'
        label: '{name}'
        label_font: Assets/Fonts/Roboto-Bold.ttf
        label_size: 12
        overlay: 'Assets/Images/automation_on.png'
      - state: ~
        label: '{name}'
        label_font: Assets/Fonts/Roboto-Bold.ttf
        label_size: 12
        overlay: 'Assets/Images/automation_off.png'
    action: 'toggle'

  - type: "scene"
    class: 'HassTile'
    states:
      - state: ~
        label: '{name}'
        label_font: Assets/Fonts/Roboto-Bold.ttf
        label_size: 12
        overlay: 'Assets/Images/scene.png'
    action: 'automation/trigger'

  - type: "temperature"
    class: 'HassTile'
    states:
      - state: ~
        label: '{name}'
        label_font: Assets/Fonts/Roboto-Bold.ttf
        label_size: 12
        value: '{state} °C'
        value_font: Assets/Fonts/Roboto-Light.ttf
        value_size: 18
        overlay: 'Assets/Images/sensor.png'
    action: ~

screens:
  - name: "home"
    tiles:
      - position: [0, 0]
        type: "light"
        name: "Study"
        entity_name: "group.study_lights"
      - position: [0, 1]
        type: "scene"
        name: "Normal"
        entity_name: "automation.bender_pausedstopped"
      - position: [1, 1]
        type: "scene"
        name: "Dim"
        entity_name: "automation.bender_playing"
      - position: [0, 2]
        type: "light"
        name: "Mr Ed"
        entity_name: "light.mr_ed"
      - position: [1, 2]
        type: "light"
        name: "Desk Lamp"
        entity_name: "light.desk_lamp"
      - position: [2, 2]
        type: "light"
        name: "Study Bias"
        entity_name: "light.study_bias"
      - position: [4, 2]
        type: "automation"
        name: "Auto Dim"
        entity_name: "group.study_automations"
      - position: [4, 0]
        type: "temperature"
        name: "Study"
        entity_name: "sensor.study_temperature"
      - position: [3, 0]
        type: "temperature"
        name: "Living Room"
        entity_name: "sensor.living_room_temperature"
      - position: [2, 0]
        type: "temperature"
        name: "Bedroom"
        entity_name: "sensor.bedroom_temperature"
      - position: [1, 0]
        type: "temperature"
        name: "Server"
        entity_name: "sensor.server_closet_temperature"
